name: TrickOrTreat
version: ${version}
main: com.halloween.trickortreat.TrickOrTreatPlugin
api-version: 1.20
authors: [YourName]
description: A Halloween-themed trick or treat plugin
softdepend: [Vault, LuckPerms]

commands:
  trickortreat:
    description: Main command for the Halloween Trick or Treat plugin
    usage: /<command> [reload|give]
    aliases: [tot, halloween]
    permission: trickortreat.admin

permissions:
  trickortreat.admin:
    description: Allows access to admin commands
    default: op
  trickortreat.use:
    description: Allows players to use Halloween candy
    default: true
