name: HalloweenTrickOrTreatSkyblock
version: '${version}'
main: com.halloween.trickortreat.TrickOrTreatPlugin
api-version: '1.20'
author: Halloween Team
description: A festive Halloween trick or treat plugin
softdepend: [Vault]

commands:
  trickortreat:
    description: Main command for the Halloween Trick or Treat plugin
    usage: /<command> [reload|give]
    aliases: [tot, halloween]
    permission: trickortreat.admin
  triggercandydrop:
    description: Trigger candy drop logic for external use (Pixelmon integration)
    usage: /<command> <player> [force-rare]
    permission: trickortreat.admin

permissions:
  trickortreat.admin:
    description: Allows access to admin commands
    default: op
  trickortreat.use:
    description: Allows players to use Halloween candy
    default: true
